# Example of a pod capable of inspecting (but not modifying) arbitrary
# kubernetes objects via kubectl.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swiss-army-knife
rules: 
  - resources: ["*"]
    apiGroups: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swiss-army-knife
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swiss-army-knife
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swiss-army-knife
subjects:
  - kind: ServiceAccount
    name: swiss-army-knife
---
apiVersion: v1
kind: Pod
metadata:
  name: swiss-army-knife-with-sa
spec:
  containers:
    - name: swiss-army-knife
      image: ghcr.io/smartsquaregmbh/swiss-army-knife:unprivileged
      command:
        - bash
        - -c 
        - "while true; do sleep 10; done"
  serviceAccountName: swiss-army-knife